// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Conversation struct {
	ID          int32        `json:"id"`
	CreatorID   uuid.UUID    `json:"creator_id"`
	RecipientID uuid.UUID    `json:"recipient_id"`
	CreatedAt   sql.NullTime `json:"created_at"`
	Status      int16        `json:"status"`
}

type Dog struct {
	ID    uuid.UUID      `json:"id"`
	Name  sql.NullString `json:"name"`
	Breed sql.NullString `json:"breed"`
}

type Message struct {
	ID             int32         `json:"id"`
	ConversationID sql.NullInt32 `json:"conversation_id"`
	SenderID       uuid.UUID     `json:"sender_id"`
	RecipientID    uuid.UUID     `json:"recipient_id"`
	MessageBody    string        `json:"message_body"`
	CreatedAt      sql.NullTime  `json:"created_at"`
}

type User struct {
	ID        uuid.UUID     `json:"id"`
	FullName  string        `json:"full_name"`
	Email     string        `json:"email"`
	Password  string        `json:"password"`
	Contact   string        `json:"contact"`
	Dog       sql.NullInt32 `json:"dog"`
	Address   string        `json:"address"`
	City      string        `json:"city"`
	PostCode  string        `json:"post_code"`
	Longitude string        `json:"longitude"`
	Latitude  string        `json:"latitude"`
	CreatedAt sql.NullTime  `json:"created_at"`
}
