version: "3.8"

services:
  db:
    container_name: db_container
    image: postgres:13.2-alpine
    # build:
    #   context: ./ # path to where the dockerfile is located
    #   dockerfile: postgres-dockerfile
    env_file:
      - ./.env
    # command: ["postgres", "-c", "log_statement=all"]
    command: ["postgres"]
    tty: true
    volumes:
      - db_postgres:/var/lib/postgresql/data/ # we want to persist the data
    ports:
      - "5444:5432"

  golang:
    container_name: golang_container
    # image: golang:1.16.5
    build:
      context: ../ # path to where the dockerfile is located
      dockerfile: docker/dockerfile
    env_file: ./.env
    # volumes:
    #   - "/home/dev/development_work/sharedDockerVolumes/golangShared/:/go/"
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db_postgres:
